swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api/simulation"

# Paths supported by the server application
paths:
  /montecarlo:
    get:
      operationId: "simulation.montecarlo"
      tags:
        - "montecarlo"
      summary: "The montecarlo data structure supported by the server application"
      description: "Run montecarlo analytics"
      responses:
        200:
          description: "Successful run montecarlo simulation"
          schema:
            type: "array"
            items:
              properties:
                fname:
                  type: "string"
                lname:
                  type: "string"
                timestamp:
                  type: "string"